### ISSUE TITLE
Fails to parse "N95W18000 Appleton Ave, Menomonee Falls, WI"

### ISSUE THREAD

**Issue by markstos** [thrustlabs/contact-parser#20]
The issue appears to be with the strange street number, which appears to real:

https://encrypted.google.com/search?hl=en&q=N95W18000%20Appleton%20Ave%2C%20Menomonee%20Falls%2C%20WI

The same address also trips up the `addressit` parser:

https://github.com/DamonOehlman/addressit/issues/16

**Comment by jasondoucette** [comment]
Yeah, that ties in with some of the issues in https://gist.github.com/wboykinm/69a89309a522d61b2d292bd4363739fc - I suspect we can expand the regex for the number term but I'm not sure how quickly that moves us into regex bandaid/whackamole territory. (No time to look this week but will pop back Monday-ish)

**Comment by jasondoucette** [comment]
@markstos I've got a test branch at https://github.com/thrustlabs/contact-parser/tree/bugfix/nonnumeric-addresses but I'm not sure if I'm adding more false positives than fixes with it, care to have a look?

**Comment by markstos** [comment]
@jasondoucette, here's some feedback:

  * Did you intended to remove the /dist/ files?
  * I saw this commit also weakened the check for a postal address, by not requiring a comma to proceed it. Is that related to improving the parsing the semi-numeric street addresses?
  * It looks like the proposed regex for a street address is a "zero or more non-spaces followed by one or more digits followed by zero or more non-spaces".  Instead checking for possible non-spaces surrounding the digit, why not use a stronger check of "word characters" (\w) or "words and digits" ([\w\d]). It seems like "non-spaces" might include unwanted things like control-characters?

**Comment by jasondoucette** [comment]
Thanks @markstos !

* Ha, how did I delete /dist/? I'm the reason software licenses say you can't use the product in a nuclear reactor.
* Not sure what you mean about the no longer required comma - if you mean the changes to `usZipRegex` the comma was always optional, now it's either "a comma and maybe some whitespace" or "some whitespace" (though looking at it now I'm thinking `(?:,\s*|\s+)` would make more sense there, changed.)
* Some trade offs in `\w` vs `\S` - `\w` only covers latin chars, but I guess we're OK until someone makes a street number with an umlaut, so I'll tighten that up.

Rebased to hide my shame :)  Thanks again!

**Comment by markstos** [comment]
Looks good to me, considering it doesn't break any of the other existing tests.
